# -*- coding: utf-8 -*-
"""DataScienceProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3yDaTtYuZy_Ks_bdNOtEvw0N2pFLhOP
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
customers = pd.read_csv("/content/Customers.csv")
products = pd.read_csv("/content/Products.csv")
transactions = pd.read_csv("/content/Transactions.csv")

# Check the first few rows
print(customers.head(), products.head(), transactions.head())

# Check for missing values
print(customers.isnull().sum())
print(products.isnull().sum())
print(transactions.isnull().sum())

# Check data types
print(customers.info(), products.info(), transactions.info())

# Summary statistics
print(transactions.describe())

# Count of customers by region
plt.figure(figsize=(8, 5))
sns.countplot(y=customers['Region'], order=customers['Region'].value_counts().index)
plt.title("Customer Count by Region")
plt.show()

# Top 10 most sold products
top_products = transactions.groupby('ProductID')['Quantity'].sum().nlargest(10)
top_products.plot(kind='bar', title="Top 10 Most Sold Products")
plt.show()

# Trend of transactions over time
transactions['TransactionDate'] = pd.to_datetime(transactions['TransactionDate'])
transactions.set_index('TransactionDate').resample('M').size().plot(title="Monthly Transaction Volume")
plt.show()
